services:
  postgres:
    image: postgres:16
    container_name: tool_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TOOL_REGISTRY_DATABASE__NAME:-toolsdb}
      POSTGRES_USER: ${TOOL_REGISTRY_DATABASE__USER:-toolsuser}
      POSTGRES_PASSWORD: ${TOOL_REGISTRY_DATABASE__PASSWORD:-toolspassword}
    ports:
      - "5432:5432"
    volumes:
      - toolsdb_postgres_data:/var/lib/postgresql/data

volumes:
  toolsdb_postgres_data:
