version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tool_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: harvester
      POSTGRES_PASSWORD: yoursecretsecret
    ports:
      - "5432:5432"
    volumes:
      - toolsdb_postgres_data:/var/lib/postgresql/data

volumes:
  toolsdb_postgres_data:
