[project]
name = "toolmeta_harvester"
version = "0.1.0-dev"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lxml>=6.0.2",
    "psycopg[binary]>=3.3.2",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.45",
]
